-- DEPRECATED: Subscriptions table removed. Run db/drop-subscriptions.sql to drop it.
-- Payment/package is now arranged via contact after signup.

-- CREATE TABLE IF NOT EXISTS public.subscriptions (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
--   plan TEXT NOT NULL CHECK (plan IN ('trial', 'Essential', 'Premium', 'Concierge')),
--   amount DECIMAL(10, 2) NOT NULL,
--   currency TEXT NOT NULL DEFAULT 'EUR',
--   status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('trial', 'pending', 'active', 'cancelled', 'expired')),
--   stripe_session_id TEXT,
--   stripe_payment_intent_id TEXT,
--   stripe_subscription_id TEXT,
--   paid_at TIMESTAMP WITH TIME ZONE,
--   expires_at TIMESTAMP WITH TIME ZONE,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--   updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );

-- CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions(user_id);
-- CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON public.subscriptions(status);
